services:
  db:
    image: postgres:16.4
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homeworkmanager
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  goose:
    build:
      context: .
      dockerfile: ./migrations/Dockerfile
    environment:
      - POSTGRES_DB_NAME=homeworkmanager
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - POSTGRES_USER=postgres
    depends_on:
      db:
        condition: service_healthy


  app:
    image: kirillzet/homeworkmanager-api:${TAG:-latest}
    build:
      context: .
    environment:
      - AUTH_TTL=1500s
      - DOMAIN=localhost
      - ENCODING_MODE=console
      - HOST=0.0.0.0
      - PORT=8888
      - POSTGRES_CONNECT_TIMEOUT=5
      - POSTGRES_DB_NAME=homeworkmanager
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - POSTGRES_USER=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      goose:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - "8888:8888"
    restart: always

volumes:
  db_data:
  redis_data:



