services:
  db:
    image: postgres:16.4
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homeworkmanager
    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - backend

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

    networks:
      - backend

    restart: always

  goose:
    build:
      context: .
      dockerfile: ./migrations/Dockerfile
    env_file:
      - db.env

    networks:
      - backend

    depends_on:
      db:
        condition: service_healthy


  nginx:
    image: nginx:latest
    networks:
      - backend
      - frontend
    depends_on:
        - backend
        - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf




  backend:
    image: ghcr.io/homeworkmanager/backend:${BACKEND_TAG:-latest}
    build:
      context: .
    env_file:
      - backend.env
    depends_on:
      goose:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - "8888:8888"

    networks:
      - backend

    restart: always

  frontend:
    image: ghcr.io/homeworkmanager/frontend:${FRONTEND_TAG:-latest}
    networks:
      - frontend
      - backend
    depends_on:
      - backend


volumes:
  db_data:
  redis_data:


networks:
  backend:
  frontend:

