// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination contract_mocks_test.go -package group
//

// Package group is a generated GoMock package.
package group

import (
	context "context"
	entity "homeworktodolist/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGroupRepo is a mock of GroupRepo interface.
type MockGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepoMockRecorder
	isgomock struct{}
}

// MockGroupRepoMockRecorder is the mock recorder for MockGroupRepo.
type MockGroupRepoMockRecorder struct {
	mock *MockGroupRepo
}

// NewMockGroupRepo creates a new mock instance.
func NewMockGroupRepo(ctrl *gomock.Controller) *MockGroupRepo {
	mock := &MockGroupRepo{ctrl: ctrl}
	mock.recorder = &MockGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepo) EXPECT() *MockGroupRepoMockRecorder {
	return m.recorder
}

// ChangeRegisterKey mocks base method.
func (m *MockGroupRepo) ChangeRegisterKey(ctx context.Context, group entity.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeRegisterKey", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeRegisterKey indicates an expected call of ChangeRegisterKey.
func (mr *MockGroupRepoMockRecorder) ChangeRegisterKey(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeRegisterKey", reflect.TypeOf((*MockGroupRepo)(nil).ChangeRegisterKey), ctx, group)
}

// Create mocks base method.
func (m *MockGroupRepo) Create(ctx context.Context, group entity.Group) (entity.GroupID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(entity.GroupID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGroupRepoMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupRepo)(nil).Create), ctx, group)
}

// GetAllGroups mocks base method.
func (m *MockGroupRepo) GetAllGroups(ctx context.Context) ([]entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGroups", ctx)
	ret0, _ := ret[0].([]entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGroups indicates an expected call of GetAllGroups.
func (mr *MockGroupRepoMockRecorder) GetAllGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGroups", reflect.TypeOf((*MockGroupRepo)(nil).GetAllGroups), ctx)
}

// GetByID mocks base method.
func (m *MockGroupRepo) GetByID(ctx context.Context, groupID entity.GroupID) (entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, groupID)
	ret0, _ := ret[0].(entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGroupRepoMockRecorder) GetByID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGroupRepo)(nil).GetByID), ctx, groupID)
}

// GetByName mocks base method.
func (m *MockGroupRepo) GetByName(ctx context.Context, name string) (entity.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(entity.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockGroupRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockGroupRepo)(nil).GetByName), ctx, name)
}
