// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination contract_mocks_test.go -package homework
//

// Package homework is a generated GoMock package.
package homework

import (
	context "context"
	entity "homeworktodolist/internal/entity"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockHomeworkRepo is a mock of HomeworkRepo interface.
type MockHomeworkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHomeworkRepoMockRecorder
	isgomock struct{}
}

// MockHomeworkRepoMockRecorder is the mock recorder for MockHomeworkRepo.
type MockHomeworkRepoMockRecorder struct {
	mock *MockHomeworkRepo
}

// NewMockHomeworkRepo creates a new mock instance.
func NewMockHomeworkRepo(ctrl *gomock.Controller) *MockHomeworkRepo {
	mock := &MockHomeworkRepo{ctrl: ctrl}
	mock.recorder = &MockHomeworkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHomeworkRepo) EXPECT() *MockHomeworkRepoMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockHomeworkRepo) Clear(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockHomeworkRepoMockRecorder) Clear(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockHomeworkRepo)(nil).Clear), ctx)
}

// Create mocks base method.
func (m *MockHomeworkRepo) Create(ctx context.Context, homework entity.Homework) (entity.HomeworkID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, homework)
	ret0, _ := ret[0].(entity.HomeworkID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHomeworkRepoMockRecorder) Create(ctx, homework any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHomeworkRepo)(nil).Create), ctx, homework)
}

// Delete mocks base method.
func (m *MockHomeworkRepo) Delete(ctx context.Context, id entity.HomeworkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHomeworkRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHomeworkRepo)(nil).Delete), ctx, id)
}

// GetByGroupAndTime mocks base method.
func (m *MockHomeworkRepo) GetByGroupAndTime(ctx context.Context, userID entity.UserID, groupID entity.GroupID, fromTime, toTime time.Time) ([]entity.Homework, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGroupAndTime", ctx, userID, groupID, fromTime, toTime)
	ret0, _ := ret[0].([]entity.Homework)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGroupAndTime indicates an expected call of GetByGroupAndTime.
func (mr *MockHomeworkRepoMockRecorder) GetByGroupAndTime(ctx, userID, groupID, fromTime, toTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGroupAndTime", reflect.TypeOf((*MockHomeworkRepo)(nil).GetByGroupAndTime), ctx, userID, groupID, fromTime, toTime)
}

// Update mocks base method.
func (m *MockHomeworkRepo) Update(ctx context.Context, id entity.HomeworkID, homeworkText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, homeworkText)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHomeworkRepoMockRecorder) Update(ctx, id, homeworkText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHomeworkRepo)(nil).Update), ctx, id, homeworkText)
}

// MockHomeworkStatusService is a mock of HomeworkStatusService interface.
type MockHomeworkStatusService struct {
	ctrl     *gomock.Controller
	recorder *MockHomeworkStatusServiceMockRecorder
	isgomock struct{}
}

// MockHomeworkStatusServiceMockRecorder is the mock recorder for MockHomeworkStatusService.
type MockHomeworkStatusServiceMockRecorder struct {
	mock *MockHomeworkStatusService
}

// NewMockHomeworkStatusService creates a new mock instance.
func NewMockHomeworkStatusService(ctrl *gomock.Controller) *MockHomeworkStatusService {
	mock := &MockHomeworkStatusService{ctrl: ctrl}
	mock.recorder = &MockHomeworkStatusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHomeworkStatusService) EXPECT() *MockHomeworkStatusServiceMockRecorder {
	return m.recorder
}

// DeleteHomeworkID mocks base method.
func (m *MockHomeworkStatusService) DeleteHomeworkID(ctx context.Context, homeworkID entity.HomeworkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHomeworkID", ctx, homeworkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHomeworkID indicates an expected call of DeleteHomeworkID.
func (mr *MockHomeworkStatusServiceMockRecorder) DeleteHomeworkID(ctx, homeworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHomeworkID", reflect.TypeOf((*MockHomeworkStatusService)(nil).DeleteHomeworkID), ctx, homeworkID)
}
