name: Push to Docker Hub

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{secrets.DOCKER_USERNAME}}/homeworkmanager-backend:${{ github.run_number }}" .

      - name: Push Docker image
        run: docker push "${{secrets.DOCKER_USERNAME}}/homeworkmanager-backend:${{ github.run_number }}"
